### ISSUE TITLE
Pylint compatibility version

### ISSUE THREAD

**Issue by usinelogicielle** [omegacen/pylint-sonarjson#1]
Hi,

Thanks for your work.
I tried to use this plugin.
Sadly I have a old pylint version (2.5). I can't upgrade the version right now.
I would like to know with which pylint version this plugin has been tested?

It'll be good to write that ,in the README

**Comment by teake** [comment]
The required Pylint version is listed in `setup.py` here: https://github.com/omegacen/pylint-sonarjson/blob/7522ad903880086c116e69e792731701dce586fc/setup.py#L25

I don't it's necessary to duplicate this information in the README.

This used to be >2.10, but I've just pushed a new version (1.0.2) that supports Pylint from 2.4. So hopefully this now works for you!
