### ISSUE TITLE
default value with pylint 2.5

### ISSUE THREAD

**Issue by usinelogicielle** [omegacen/pylint-sonarjson#2]
Sorry me again.

Thank you for the correction. I have a result now with this version.
But all issues are with the severity to MINOR.
Even if I configure the rules with sonar-rules options.

I'm debugging the code and I think it's in this line :

https://github.com/omegacen/pylint-sonarjson/blob/7522ad903880086c116e69e792731701dce586fc/src/pylint_sonarjson/sonaroptions_checker.py#L129

The msg_id return is None, so the dicts are with default value. I tested with return msg_id and it seems to work.
But of course, there are not check if this is exist in pylint way.

Do you want a PR or could you make the correction?

**Comment by teake** [comment]
Thanks for reporting this. You're right, that was an oversight on part. Should be fixed with 1.0.3.
